version: '3'
services: 
    web:
      build: 
        context: .  # this context specify where we find
                    # all the file and folder for this image we pulled from 

        dockerfile: Dockerfile.dev
      ports:
         - "3000:3000"
      volumes:
        - /usr/app/node_modules
        - .:/usr/app

    tests:
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes: 
        - /usr/app/node_modules
        - .:/usr/app
      command: ["npm","run","test"]  

